"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Candle = { date: string; open: number; high: number; low: number; close: number };
type Position = { quantity: number; avgEntry: number };
type State = { joined: true; username: string; game: { gameId: string; status: string; index: number; maxIndex: number }; symbols: string[]; symbol: string; candles: Candle[]; prices: Record<string, number>; portfolio: { cash: number; positions: Record<string, Position> }; totalValue: number; leaderboard: { username: string; totalValue: number }[] };
const rupees = (amount: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(amount);

function Candles({ candles }: { candles: Candle[] }) {
  if (!candles.length) return <div className="chart-empty">Waiting for the first revealed candle.</div>;
  const width = 860, height = 360, pad = 24, values = candles.flatMap((c) => [c.high, c.low]), low = Math.min(...values), high = Math.max(...values), range = high - low || 1;
  const y = (value: number) => pad + ((high - value) / range) * (height - pad * 2), unit = Math.max(3, (width - pad * 2) / candles.length), start = Math.max(0, candles.length - 90), visible = candles.slice(start);
  return <svg className="chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Price candlestick chart"><line x1={pad} x2={width - pad} y1={height - pad} y2={height - pad} className="grid" />{visible.map((c, i) => { const x = pad + (i + .5) * ((width - pad * 2) / visible.length), rising = c.close >= c.open, color = rising ? "#26d6a5" : "#ff6773"; return <g key={c.date}><line x1={x} x2={x} y1={y(c.high)} y2={y(c.low)} stroke={color} /><rect x={x - unit * .28} y={y(Math.max(c.open, c.close))} width={Math.max(2, unit * .56)} height={Math.max(2, Math.abs(y(c.open) - y(c.close)))} fill={color} /></g>; })}</svg>;
}

export default function Home() {
  const [mounted, setMounted] = useState(false);
  const [state, setState] = useState<State | null>(null), [username, setUsername] = useState(""), [symbol, setSymbol] = useState(""), [quantity, setQuantity] = useState(10), [notice, setNotice] = useState(""), [joining, setJoining] = useState(false), [tab, setTab] = useState<"trade" | "portfolio" | "leaderboard">("trade");
  const load = useCallback(async (requestedSymbol?: string) => { const response = await fetch(`/api/state${requestedSymbol ? `?symbol=${requestedSymbol}` : ""}`, { cache: "no-store" }); const body = await response.json(); if (body.joined) { setState(body); setSymbol(body.symbol); } else if (body.error) setNotice(body.error); }, []);
  useEffect(() => { setMounted(true); load(); const timer = setInterval(() => load(symbol), 10_000); return () => clearInterval(timer); }, [load, symbol]);
  async function join(event: FormEvent) { event.preventDefault(); setJoining(true); setNotice(""); const response = await fetch("/api/join", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username }) }); const body = await response.json(); setJoining(false); if (!response.ok) return setNotice(body.error); await load(); }
  async function order(side: "buy" | "sell") { setNotice(""); const response = await fetch("/api/trade", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ symbol, side, quantity }) }); const body = await response.json(); setNotice(response.ok ? `✓ ${body.message}` : body.error); if (response.ok) await load(symbol); }
  const last = state?.candles.at(-1)?.close ?? 0, previous = state?.candles.at(-2)?.close ?? last, change = last - previous;
  const rows = useMemo(() => state ? Object.entries(state.portfolio.positions).map(([ticker, position]) => { const px = state.prices[ticker] ?? 0; const value = position.quantity * px; return { ticker, ...position, value, pnl: value - position.quantity * position.avgEntry }; }) : [], [state]);

  if (!mounted) return null;

  if (!state) return <main className="welcome"><section><p className="kicker">MARKET<span>ARENA</span></p><h1>Trade the market.<br />Own the leaderboard.</h1><p className="subtitle">A live, room-only investing competition. Pick your game username to enter.</p><form onSubmit={join}><label>GAME USERNAME<input value={username} onChange={(e) => setUsername(e.target.value)} placeholder="e.g. AlphaBull" maxLength={24} /></label><button disabled={joining}>{joining ? "Joining…" : "Enter competition"}</button></form>{notice && <p className="notice">{notice}</p>}<p className="fine">No password required. Your browser keeps your room session.</p></section><aside><div className="stat">₹100,000 <span>starting cash</span></div><div className="stat">0 <span>starting holdings</span></div><div className="stat">Long + short <span>market orders</span></div></aside></main>;
  return <main className="shell"><header><div><p className="brand">MARKET<span>ARENA</span></p><p className="muted">Live trading competition · {state.game.gameId}</p></div><div className="user"><b>{state.username}</b><span>{state.game.status === "running" ? "● MARKET OPEN" : "● MARKET WAITING"}</span></div></header><section className="metrics"><article><small>Portfolio value</small><strong>{rupees(state.totalValue)}</strong></article><article><small>Cash balance</small><strong>{rupees(state.portfolio.cash)}</strong></article><article><small>Simulation clock</small><strong>Candle {state.game.index + 1}<em> / {state.game.maxIndex + 1}</em></strong></article><article><small>Buying & shorting</small><strong>Market enabled</strong></article></section><nav><button className={tab === "trade" ? "active" : ""} onClick={() => setTab("trade")}>Trade</button><button className={tab === "portfolio" ? "active" : ""} onClick={() => setTab("portfolio")}>Portfolio</button><button className={tab === "leaderboard" ? "active" : ""} onClick={() => setTab("leaderboard")}>Leaderboard</button></nav>{notice && <p className="notice">{notice}</p>}{tab === "leaderboard" ? <section className="panel"><h2>Live leaderboard</h2><table><thead><tr><th>Rank</th><th>Trader</th><th>Portfolio value</th></tr></thead><tbody>{state.leaderboard.map((entry, i) => <tr key={entry.username} className={entry.username === state.username ? "self" : ""}><td>#{i + 1}</td><td>{entry.username}</td><td>{rupees(entry.totalValue)}</td></tr>)}</tbody></table></section> : tab === "portfolio" ? <Positions rows={rows} /> : <section className="trade-grid"><article className="panel chart-panel"><div className="quote"><div><select value={symbol} onChange={(e) => load(e.target.value)}>{state.symbols.map((item) => <option key={item}>{item}</option>)}</select><span>Daily · revealed market history</span></div><strong>{rupees(last)} <em className={change >= 0 ? "up" : "down"}>{change >= 0 ? "+" : ""}{change.toFixed(2)}</em></strong></div><Candles candles={state.candles} /></article><aside className="ticket"><p className="ticket-title">Place market order</p><p className="muted">Executes at the latest revealed close.</p><label>Quantity<input type="number" min="1" value={quantity} onChange={(e) => setQuantity(Math.max(1, Number(e.target.value)))} /></label><p className="estimate">Estimated value <b>{rupees(quantity * last)}</b></p><button className="buy" onClick={() => order("buy")}>Market buy</button><button className="sell" onClick={() => order("sell")}>Market sell / short</button><p className="fine">Selling beyond your current holding opens a short position.</p></aside></section>} {tab === "trade" && <Positions rows={rows} />}</main>;
}
function Positions({ rows }: { rows: { ticker: string; quantity: number; avgEntry: number; value: number; pnl: number }[] }) { return <section className="panel positions"><h2>Open positions</h2>{rows.length ? <table><thead><tr><th>Symbol</th><th>Quantity</th><th>Average entry</th><th>Market value*</th><th>Unrealized P/L*</th></tr></thead><tbody>{rows.map((row) => <tr key={row.ticker}><td><b>{row.ticker}</b></td><td className={row.quantity < 0 ? "down" : "up"}>{row.quantity < 0 ? `SHORT ${Math.abs(row.quantity)}` : row.quantity}</td><td>{rupees(row.avgEntry)}</td><td>{row.value ? rupees(row.value) : "Refresh quote"}</td><td className={row.pnl >= 0 ? "up" : "down"}>{row.value ? rupees(row.pnl) : "—"}</td></tr>)}</tbody></table> : <p className="empty">No open positions. Your portfolio begins at ₹100,000 cash and zero holdings.</p>}<p className="fine">* Refreshing a quote marks all positions to the active candle close.</p></section>; }
